# https://hub.docker.com/r/linuxserver/calibre

FROM linuxserver/calibre:latest
MAINTAINER EXP

ENV PUID=1000
ENV PGID=1000
ENV TZ=Aisa/Shanghai
ENV UMASK_SET=022
ENV GUAC_USER=admin
ENV GUAC_PASS=0192023a7bbd73250516f069df18b500
# echo -n admin123 | openssl md5

EXPOSE 8080
EXPOSE 8081
WORKDIR /
