# https://hub.docker.com/r/linuxserver/calibre-web

FROM linuxserver/calibre-web:latest
MAINTAINER EXP

ENV PUID=1000
ENV PGID=1000
ENV TZ=Aisa/Shanghai
ENV DOCKER_MODS=linuxserver/calibre-web:calibre

EXPOSE 8083
WORKDIR /
